// Mocks generated by Mockito 5.0.15 from annotations
// in funda_sample/test/data/repository/remote/house_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:funda_sample/utils/network/network_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [NetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkService extends _i1.Mock implements _i2.NetworkService {
  MockNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> get(
          {String? url,
          Map<String, String>? headers,
          Map<String, String>? queries}) =>
      (super.noSuchMethod(
          Invocation.method(
              #get, [], {#url: url, #headers: headers, #queries: queries}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> post(
          {String? url,
          Map<String, String>? headers,
          Map<String, dynamic>? body}) =>
      (super.noSuchMethod(
          Invocation.method(
              #post, [], {#url: url, #headers: headers, #body: body}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> put(
          {String? url,
          Map<String, String>? headers,
          Map<String, dynamic>? body}) =>
      (super.noSuchMethod(
          Invocation.method(
              #put, [], {#url: url, #headers: headers, #body: body}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> delete(
          {String? url,
          Map<String, String>? headers,
          Map<String, dynamic>? body}) =>
      (super.noSuchMethod(
          Invocation.method(
              #delete, [], {#url: url, #headers: headers, #body: body}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  String toString() => super.toString();
}
