// Mocks generated by Mockito 5.0.15 from annotations
// in funda_sample/test/screens/home/home_viewmodel_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:funda_sample/data/models/responses/house.dart' as _i3;
import 'package:funda_sample/data/repository/remote/house_repository.dart'
    as _i4;
import 'package:funda_sample/utils/network/network_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeNetworkService_0 extends _i1.Fake implements _i2.NetworkService {}

class _FakeHouseResponseModel_1 extends _i1.Fake
    implements _i3.HouseResponseModel {}

/// A class which mocks [HouseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHouseRepository extends _i1.Mock implements _i4.HouseRepository {
  MockHouseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NetworkService get networkService =>
      (super.noSuchMethod(Invocation.getter(#networkService),
          returnValue: _FakeNetworkService_0()) as _i2.NetworkService);
  @override
  _i5.Future<_i3.HouseResponseModel> fetchHouseDetails(
          String? key, String? id) =>
      (super.noSuchMethod(Invocation.method(#fetchHouseDetails, [key, id]),
              returnValue: Future<_i3.HouseResponseModel>.value(
                  _FakeHouseResponseModel_1()))
          as _i5.Future<_i3.HouseResponseModel>);
  @override
  String toString() => super.toString();
}
